services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: provisioning_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/provisioning
      SWITCH_SSH_USER: admin
      SWITCH_SSH_PASS: TuPassword
      SWITCH_SSH_SECRET: ""
      SWITCH_DEVICE_TYPE: cisco_ios
    volumes:
      - ./data:/data
      - /home/carlovalle/Open_PnP_Server/configs:/Open_PnP_Server/configs

  db:
    image: postgres:15
    container_name: provisioning_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: provisioning
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
